const seed={
  districts:[
    {id:"dhaka",name:"ঢাকা",en:"Dhaka",division:"ঢাকা",region:"পূর্ববঙ্গ",famous:["রাজধানী","পুরান ঢাকা","বাণিজ্য ও সংস্কৃতি"],food:["বাকরখানি","কাচ্চি"],places:["লালবাগ কেল্লা","আহসান মঞ্জিল","জাতীয় সংসদ ভবন"],river:["বুড়িগঙ্গা","তুরাগ"],area:"প্রশাসনিক তথ্য",upazila:"৫",est:"১৭৭২",history:"ঢাকা বাংলাদেশের রাজধানী ও রাজনৈতিক-সাংস্কৃতিক কেন্দ্র।",img:"https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=900&q=80"},
    {id:"bogura",name:"বগুড়া",en:"Bogura",division:"রাজশাহী",region:"উত্তরবঙ্গ",famous:["বগুড়ার দই","মহাস্থানগড়","আলু ও কৃষিপণ্য"],food:["দই"],places:["মহাস্থানগড়"],river:["করতোয়া"],area:"২,৮৯৮.৬৮ বর্গ কিমি",upazila:"১২",est:"১৮২১",history:"প্রাচীন পুন্ড্রবর্ধন অঞ্চলের গুরুত্বপূর্ণ অংশ হিসেবে বগুড়ার ঐতিহাসিক গুরুত্ব রয়েছে।",img:"https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=900&q=80"},
    {id:"comilla",name:"কুমিল্লা",en:"Cumilla",division:"চট্টগ্রাম",region:"পূর্ববঙ্গ",famous:["রসমালাই","ময়নামতি","খাদি"],food:["রসমালাই"],places:["শালবন বিহার","ময়নামতি"],river:["গোমতী"],area:"৩,০৮৭.৩৩ বর্গ কিমি",upazila:"১৭",est:"১৭৯০",history:"ময়নামতি-লালমাই প্রত্নাঞ্চলের জন্য কুমিল্লা বিশেষভাবে পরিচিত।",img:"https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=900&q=80"},
    {id:"sylhet",name:"সিলেট",en:"Sylhet",division:"সিলেট",region:"পূর্ববঙ্গ",famous:["চা","হাওর","পাথর"],food:["সাতকরা"],places:["জাফলং","রাতারগুল","শাহজালাল (র.) মাজার"],river:["সুরমা","কুশিয়ারা"],area:"প্রশাসনিক তথ্য",upazila:"১৩",est:"১৭৮২",history:"সিলেটের ইতিহাসে সুফি ঐতিহ্য ও চা-অর্থনীতির গুরুত্বপূর্ণ ভূমিকা রয়েছে।",img:"https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=80"},
    {id:"khulna",name:"খুলনা",en:"Khulna",division:"খুলনা",region:"দক্ষিণবঙ্গ",famous:["সুন্দরবন","চিংড়ি","শিল্প"],food:["চিংড়ি"],places:["সুন্দরবন","রূপসা নদীর তীর"],river:["রূপসা","ভৈরব"],area:"প্রশাসনিক তথ্য",upazila:"৯",est:"১৮৮২",history:"দক্ষিণ-পশ্চিমাঞ্চলের নদী, বন্দর ও সুন্দরবনকেন্দ্রিক অর্থনীতি খুলনার পরিচয়ের গুরুত্বপূর্ণ অংশ।",img:"https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=900&q=80"},
    {id:"chattogram",name:"চট্টগ্রাম",en:"Chattogram",division:"চট্টগ্রাম",region:"পূর্ববঙ্গ",famous:["সমুদ্রবন্দর","পাহাড়","সমুদ্র"],food:["মেজবান"],places:["পতেঙ্গা","চট্টগ্রাম পাহাড়ি এলাকা"],river:["কর্ণফুলী"],area:"প্রশাসনিক তথ্য",upazila:"১৫",est:"১৬৬৬",history:"চট্টগ্রাম বাংলাদেশের প্রধান সমুদ্রবন্দর ও গুরুত্বপূর্ণ পাহাড়-সমুদ্রভিত্তিক অঞ্চল।",img:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80"}
  ],
  divisions:["ঢাকা","চট্টগ্রাম","রাজশাহী","খুলনা","বরিশাল","সিলেট","রংপুর","ময়মনসিংহ"],
  sectors:[
    ["১","মেজর জিয়াউর রহমান (প্রাথমিক পর্যায়)","চট্টগ্রাম ও পার্বত্য চট্টগ্রাম"],
    ["২","মেজর খালেদ মোশাররফ","ঢাকা, কুমিল্লা ও নোয়াখালী অঞ্চলের অংশ"],
    ["৩","মেজর কে. এম. শফিউল্লাহ","সিলেট, কিশোরগঞ্জ ও আশপাশ"],
    ["৪","মেজর সি. আর. দত্ত","সিলেটের পূর্বাঞ্চল"],
    ["৫","মেজর মীর শওকত আলী","সিলেটের উত্তরাঞ্চল"],
    ["৬","উইং কমান্ডার এম. খদেমুল বাশার","রংপুর ও দিনাজপুরের অংশ"],
    ["৭","মেজর নাজমুল হক","রাজশাহী, পাবনা, বগুড়া ও আশপাশ"],
    ["৮","মেজর আবু ওসমান চৌধুরী","কুষ্টিয়া, যশোর, খুলনা ও ফরিদপুরের অংশ"],
    ["৯","মেজর এম. এ. জলিল","বরিশাল ও পটুয়াখালীসহ দক্ষিণাঞ্চল"],
    ["১০","নৌ-কমান্ডো","নৌ অভিযান; স্থল সীমানা নির্ধারিত ছিল না"],
    ["১১","মেজর আবু তাহের","ময়মনসিংহ, টাঙ্গাইল ও আশপাশ"]
  ]
};
let db=JSON.parse(localStorage.getItem("bdxDB")||"null")||seed;
let fav=JSON.parse(localStorage.getItem("bdxFav")||"[]");
let current="home";

const photos=[
 ["ঢাকা","https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=600&q=80"],
 ["চট্টগ্রাম","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80"],
 ["সিলেট","https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80"],
 ["রাজশাহী","https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=600&q=80"],
 ["খুলনা","https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=600&q=80"],
 ["বরিশাল","https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=600&q=80"]
];

function esc(x=""){return String(x).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function save(){localStorage.setItem("bdxDB",JSON.stringify(db))}
function go(page,arg=""){current=page;let m=document.getElementById("main");if(page==="home")m.innerHTML=home();if(page==="map")m.innerHTML=map();if(page==="districts")m.innerHTML=districts();if(page==="detail")m.innerHTML=detail(arg);if(page==="knowledge")m.innerHTML=knowledge();if(page==="quiz")m.innerHTML=quiz();window.scrollTo({top:0,behavior:"smooth"})}
function toggleMenu(){document.getElementById("sideMenu").classList.toggle("open")}
function toggleTheme(){document.body.classList.toggle("dark");localStorage.setItem("bdxTheme",document.body.classList.contains("dark")?"dark":"light")}
if(localStorage.getItem("bdxTheme")==="dark")document.body.classList.add("dark")
function focusSearch(){document.getElementById("homeSearch")?.focus();window.scrollTo({top:0,behavior:"smooth"})}
function search(q){q=q.toLowerCase().trim();let a=db.districts.filter(d=>(d.name+" "+d.en+" "+d.division+" "+d.region+" "+d.famous.join(" ")+" "+d.food.join(" ")+" "+d.places.join(" ")+" "+d.river.join(" ")).toLowerCase().includes(q));document.getElementById("searchResults").innerHTML=a.length?a.map(card).join(""):`<div class="detail-card">কোনো তথ্য পাওয়া যায়নি।</div>`}
function card(d){return `<div class="list-card" onclick="go('detail','${d.id}')"><div style="font-size:25px">📍</div><h3>${esc(d.name)}</h3><p>${esc(d.division)} বিভাগ • ${esc(d.region)}</p><span class="tag">${esc(d.famous[0])}</span></div>`}
function quick(i,t,action){return `<button class="quick" onclick="${action}"><span class="ico">${i}</span><b>${t}</b></button>`}
function home(){
 return `<section class="hero"><div class="hero-content"><div class="tag">🇧🇩 আমার বাংলাদেশ</div><h1>বাংলাদেশ <span>Explorer</span></h1><p>৬৪ জেলার ইতিহাস, সংস্কৃতি, খাবার, মানুষ ও পর্যটন—একটি interactive knowledge map-এ।</p><div class="search"><input id="homeSearch" placeholder="জেলা, বিভাগ, স্থান, খাবার, মানুষ খুঁজুন..." onkeydown="if(event.key==='Enter')search(this.value)"><button onclick="search(document.getElementById('homeSearch').value)">খুঁজুন</button></div></div></section>
 <div class="quick-grid">
 ${quick("🗺️","ইন্টার‌্যাক্টিভ ম্যাপ","go('map')")}${quick("🇧🇩","৬৪ জেলা","go('districts')")}${quick("🏛️","৮ বিভাগ","go('map')")}${quick("🌍","৪ অঞ্চল","go('map')")}${quick("📚","বাংলাদেশ জ্ঞান","go('knowledge')")}${quick("🏝️","পর্যটন স্থান","go('districts')")}${quick("👤","বিখ্যাত মানুষ","go('districts')")}${quick("🍛","ঐতিহ্যবাহী খাবার","search('দই')")}
 ${quick("🪖","মুক্তিযুদ্ধ","go('knowledge')")}${quick("📜","১১ সেক্টর","go('knowledge')")}${quick("📄","সংবিধান","go('knowledge')")}${quick("💼","সরকারি চাকরি","go('knowledge')")}${quick("🌊","নদী ও প্রকৃতি","go('map')")}${quick("🎭","সংস্কৃতি","go('districts')")}${quick("🎓","শিক্ষা প্রতিষ্ঠান","go('districts')")}${quick("⚽","খেলাধুলা","go('districts')")}${quick("🏆","কুইজ","go('quiz')")}${quick("•••","আরও","showMore()")}
 </div>
 ${mapHome()}
 ${sectionTitle("জনপ্রিয় জেলা","সব জেলা দেখুন",()=>go("districts"))}
 <div class="thumb-row">${photos.map(p=>`<div class="thumb" style="background-image:url('${p[1]}')" onclick="search('${p[0]}')"><b>${p[0]}</b></div>`).join("")}</div>
 <div class="section-title"><h2>🏝️ বাংলাদেশের পর্যটন স্থান</h2><p>সব দেখুন →</p></div>
 <div class="cards-3">${photoCard("কক্সবাজার","সমুদ্র ও পর্যটন","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80")}${photoCard("জাফলং","পাহাড় ও নদী","https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=800&q=80")}${photoCard("সুন্দরবন","বন ও বন্যপ্রাণী","https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=800&q=80")}</div>
 <div class="section-title"><h2>🍛 ঐতিহ্যবাহী খাবার</h2><p>সব দেখুন →</p></div>
 <div class="cards-3">${photoCard("বগুড়ার দই","বগুড়া • উত্তরবঙ্গ","https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80")}${photoCard("রসমালাই","কুমিল্লা • পূর্ববঙ্গ","https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80")}${photoCard("মেজবান","চট্টগ্রাম • পূর্ববঙ্গ","https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=800&q=80")}</div>
 ${knowledgeStrip()} ${quizStrip()} ${footer()}`;
}
function mapHome(){return `<div class="section-title"><h2>🗺️ বাংলাদেশের ইন্টার‌্যাক্টিভ মানচিত্র</h2><button class="btn light" onclick="go('map')">Explore Map</button></div><div class="map-layout"><div class="map-panel"><div class="map-title"><h2>বাংলাদেশের ইন্টার‌্যাক্টিভ মানচিত্র</h2><p>জেলা, বিভাগ ও অঞ্চল অনুযায়ী Explore করুন</p></div><div class="map-tools"><button>+</button><button>−</button><button>⌾</button></div><div class="bd-map">${["rangpur","mymensingh","sylhet","rajshahi","dhaka","khulna","barishal","chattogram"].map((x,i)=>`<div class="division ${x}" onclick="mapDivision('${db.divisions[i]}')">${db.divisions[i]}</div>`).join("")}</div><div class="map-bottom"><button class="active">📍 বিভাগ অনুযায়ী</button><button>▱ অঞ্চল অনুযায়ী</button><button>≋ নদী দেখান</button><button>◉ জেলা নাম</button></div></div><div class="panel"><div class="panel-head"><div><b>বগুড়া জেলা</b><div class="subline">রাজশাহী বিভাগ • উত্তরবঙ্গ</div></div><button class="btn" onclick="go('detail','bogura')">বিস্তারিত দেখুন →</button></div><div class="district-feature"><div class="district-photo" style="background-image:url('${db.districts.find(x=>x.id==="bogura").img}')"><div class="photo-label">📍 মহাস্থানগড়, বগুড়া</div></div><div class="mini-grid">${mini("▤","ইতিহাস")}${mini("▧","দর্শনীয় স্থান")}${mini("♟","খ্যাতিমান মানুষ")}${mini("🍛","ঐতিহ্যবাহী খাবার")}${mini("🎓","শিক্ষা প্রতিষ্ঠান")}${mini("⚙","শিল্প ও পণ্য")}</div><div class="panel-head" style="margin:12px -14px 0"><b>🌿 প্রাথমিক তথ্য</b><button class="btn light" onclick="go('detail','bogura')">সম্পূর্ণ তথ্য →</button></div><div class="data-list">${row("বিভাগ","রাজশাহী")}${row("অঞ্চল","উত্তরবঙ্গ")}${row("জেলা প্রতিষ্ঠা","১৮২১")}${row("উপজেলা","১২টি")}${row("পৌরসভা","১২টি")}${row("ইউনিয়ন","১০৮টি")}${row("আয়তন","২,৮৯৮.৬৮ বর্গ কিমি")}${row("গুরুত্বপূর্ণ নদী","করতোয়া")}</div></div></div>`}
function sectionTitle(a,b,fn){return `<div class="section-title"><h2>${a}</h2><button class="btn light" onclick="(${fn.toString()})()">${b} →</button></div>`}
function mini(i,t){return `<div class="mini"><span>${i}</span><b>${t}</b></div>`}
function row(a,b){return `<div class="row"><span>${a}</span><b>${b}</b></div>`}
function photoCard(t,s,img){return `<div class="photo-card"><div class="pic" style="background-image:url('${img}')"></div><div class="body"><h3>${t}</h3><p>${s}</p></div></div>`}
function knowledgeStrip(){return `<div class="section knowledge"><div class="section-title" style="margin:0 0 10px"><h2>📚 বাংলাদেশ জ্ঞান</h2><p style="color:#9bc8ba">ইতিহাস, সংবিধান, মুক্তিযুদ্ধ, সরকার, চাকরি ও আরও অনেক কিছু</p></div><div class="knowledge-grid">${["🪖 ১১ সেক্টর","📜 সংবিধান","🇧🇩 মুক্তিযুদ্ধ","🏛️ জাতীয় দিবস","💼 সরকারি চাকরি","▤ বাংলাদেশের ইতিহাস"].map((x,i)=>`<button class="know k${i+1}" onclick="go('knowledge')"><b>${x}</b></button>`).join("")}</div></div>`}
function quizStrip(){return `<div class="section quiz"><div class="panel question"><div class="section-title" style="margin:0"><h2>🎯 কুইজ খেলুন</h2><span>১/১০</span></div><h3>বাংলাদেশের কয়টি জেলা?</h3><div class="answers"><button class="answer">A. ৬৪টি</button><button class="answer correct">B. ৬৪টি ✓</button><button class="answer">C. ৬৬টি</button><button class="answer">D. ৬৮টি</button></div><button class="btn" style="width:100%;margin-top:10px" onclick="go('quiz')">পরবর্তী প্রশ্ন →</button></div><div class="panel" style="padding:20px;background:linear-gradient(145deg,#e8f7f1,#fff)"><h2>🇧🇩 Explore Bangladesh</h2><p>একটি জেলা বেছে নিন, তথ্য জানুন, favorite করুন এবং ৬৪ জেলা Explorer badge unlock করুন।</p><button class="btn" onclick="go('districts')">Explore Now</button></div></div>`}
function districts(){return `<div class="section-title"><div><h2>📍 ৬৪ জেলা</h2><p>বিভাগ, অঞ্চল ও বিখ্যাত বিষয় অনুযায়ী খুঁজুন</p></div></div><div class="search" style="max-width:none;border:1px solid var(--line);box-shadow:none"><input id="dsearch" placeholder="জেলার নাম লিখুন..." oninput="filterDistrict(this.value)"><button>🔎</button></div><div id="dgrid" class="list-grid section">${db.districts.map(card).join("")}</div>${footer()}`}
function filterDistrict(q){let a=db.districts.filter(d=>(d.name+" "+d.en+" "+d.division+" "+d.region+" "+d.famous.join(" ")).toLowerCase().includes(q.toLowerCase()));document.getElementById("dgrid").innerHTML=a.length?a.map(card).join(""):"<div class='detail-card'>কোনো জেলা পাওয়া যায়নি।</div>"}
function map(){return `<div class="section-title"><div><h2>🗺️ Interactive Map</h2><p>বিভাগে tap করুন, তারপর district explore করুন</p></div></div>${mapHome()}${footer()}`}
function mapDivision(d){go("districts");setTimeout(()=>{document.getElementById("dsearch").value=d;filterDistrict(d)},50)}
function detail(id){let d=db.districts.find(x=>x.id===id);if(!d)return `<div class="detail-card">তথ্য পাওয়া যায়নি।</div>`;let saved=fav.includes(id);return `<div class="detail-banner"><div><span>${esc(d.en)}</span><h1>${esc(d.name)}</h1><p>${esc(d.division)} বিভাগ • ${esc(d.region)}</p></div><div><button class="btn light" onclick="toggleFav('${id}')">${saved?"❤️ Saved":"♡ Favorite"}</button><button class="btn" onclick="share('${id}')">↗ Share</button></div></div><div class="detail-grid">${detailCard("▤","প্রশাসনিক তথ্য",`বিভাগ: ${d.division}<br>অঞ্চল: ${d.region}<br>প্রতিষ্ঠা: ${d.est}<br>উপজেলা: ${d.upazila}<br>আয়তন: ${d.area}`)}${detailCard("⭐","এই জেলা কিসের জন্য বিখ্যাত",d.famous.map(x=>`<span class="tag">${x}</span>`).join(""))}${detailCard("🍛","বিখ্যাত খাবার",d.food.map(x=>`<span class="tag">${x}</span>`).join(""))}${detailCard("🏞️","দর্শনীয় স্থান",d.places.map(x=>`<p>• ${x}</p>`).join(""))}${detailCard("🌊","নদী",d.river.map(x=>`<span class="tag">${x}</span>`).join(""))}${detailCard("📜","ইতিহাস",d.history)}${detailCard("👤","বিখ্যাত মানুষ","ছবি, পরিচয় ও জেলার সম্পর্ক Admin Panel থেকে যোগ করা যাবে।")}${detailCard("🇧🇩","মুক্তিযুদ্ধ","যুদ্ধ, বধ্যভূমি, গণকবর ও মুক্তিযোদ্ধাদের verified তথ্য যোগযোগ্য।")}${detailCard("🌾","কৃষি ও পণ্য","কৃষিপণ্য, শিল্প, রপ্তানি ও ঐতিহ্যবাহী পেশা যোগযোগ্য।")}</div>${footer()}`}
function detailCard(i,t,c){return `<article class="detail-card"><div style="font-size:27px">${i}</div><h3>${t}</h3><div>${c}</div></article>`}
function toggleFav(id){if(fav.includes(id))fav=fav.filter(x=>x!==id);else fav.push(id);localStorage.setItem("bdxFav",JSON.stringify(fav));go("detail",id)}
async function share(id){let d=db.districts.find(x=>x.id===id),txt=`🇧🇩 ${d.name} — Bangladesh Explorer\n${d.division} বিভাগ • ${d.region}`;if(navigator.share)await navigator.share({title:d.name,text:txt});else{await navigator.clipboard?.writeText(txt);alert("Share text copied")}}
function knowledge(){return `<div class="section-title"><div><h2>📚 বাংলাদেশ জ্ঞান</h2><p>মুক্তিযুদ্ধ, ১১ সেক্টর, সংবিধান, ইতিহাস, রাষ্ট্রব্যবস্থা ও চাকরি প্রস্তুতি</p></div></div><div class="list-grid">${["📜 সংবিধান","🪖 ১১ সেক্টর","🇧🇩 মুক্তিযুদ্ধ","🗣️ ভাষা আন্দোলন","⏳ বাংলাদেশের ইতিহাস","🏛️ রাষ্ট্রীয় প্রতিষ্ঠান","🗳️ নির্বাচন ব্যবস্থা","🏢 স্থানীয় সরকার","🏅 জাতীয় প্রতীক","💼 সরকারি চাকরি ও BCS","🌊 নদী ও ভূগোল","🎭 লোকসংস্কৃতি"].map(x=>`<div class="list-card"><div style="font-size:27px">${x.slice(0,2)}</div><h3>${x.slice(3)}</h3><p>Admin Panel থেকে verified content, source, ছবি ও বিস্তারিত section যোগ করা যাবে।</p></div>`).join("")}</div><div class="section panel" style="padding:18px"><h2>🪖 ১১ সেক্টর</h2>${db.sectors.map(s=>`<div class="row"><b>সেক্টর ${s[0]}</b><span>${s[1]} • ${s[2]}</span></div>`).join("")}<div class="footer">সেক্টর তথ্য publication-এর আগে সরকারি/প্রামাণিক মুক্তিযুদ্ধ বিষয়ক উৎস দিয়ে যাচাই করতে হবে।</div></div><div class="section panel" style="padding:18px"><h2>📜 সংবিধান</h2><p>প্রস্তাবনা, মৌলিক অধিকার, রাষ্ট্র পরিচালনার মূলনীতি, রাষ্ট্রপতি, প্রধানমন্ত্রী ও মন্ত্রিসভা, জাতীয় সংসদ, বিচার বিভাগ, নির্বাচন, স্থানীয় সরকার, সাংবিধানিক প্রতিষ্ঠান ও তফসিল—সবগুলো আলাদা knowledge module হিসেবে রাখা হবে।</p></div>${footer()}`}
function quiz(){let q=[["বাংলাদেশের কয়টি জেলা?",["৬৪টি","৬২টি","৬৬টি","৬৮টি"],0],["বগুড়া কোন বিভাগের?",["ঢাকা","রাজশাহী","খুলনা","সিলেট"],1],["মুক্তিযুদ্ধে কতটি সেক্টর ছিল?",["৭","৯","১১","১৩"],2]][Math.floor(Math.random()*3)];return `<div class="panel" style="max-width:760px;margin:20px auto;padding:20px"><div class="section-title"><h2>🎯 বাংলাদেশ GK Quiz</h2><span>নতুন প্রশ্ন</span></div><h2>${q[0]}</h2>${q[1].map((x,i)=>`<button class="answer" style="width:100%;margin:5px 0" onclick="answer(this,${i},${q[2]})">${String.fromCharCode(65+i)}. ${x}</button>`).join("")}<p id="quizmsg"></p><button class="btn" onclick="go('quiz')">আরেকটি প্রশ্ন →</button></div>${footer()}`}
function answer(el,i,c){el.classList.toggle("correct",i===c);document.getElementById("quizmsg").textContent=i===c?"🎉 সঠিক উত্তর!":"❌ ভুল উত্তর।"}
function showMore(){openAdmin()}
function footer(){return `<div class="footer">© <b>Raju Ahammed</b> — Bangladesh Explorer • <a href="https://t.me/r366grp" target="_blank">@r366grp</a></div>`}

/* ADMIN CMS */
function openAdmin(){let m=document.getElementById("modal");m.classList.remove("hidden");m.innerHTML=`<div class="modal-box"><div class="modal-head"><h2>🔐 Admin Panel</h2><button class="close" onclick="closeModal()">✕</button></div><div id="adminBody"><div class="form"><label>Admin Code</label><input id="adminCode" type="password" placeholder="Code"><button class="btn" onclick="adminLogin()">Login</button><small id="loginMsg"></small></div></div></div>`}
function closeModal(){document.getElementById("modal").classList.add("hidden")}
function adminLogin(){let code=document.getElementById("adminCode").value;if(code==="Raju366")adminDashboard();else document.getElementById("loginMsg").textContent="ভুল code। Production-এ secure backend authentication ব্যবহার করতে হবে।"}
function adminDashboard(){document.getElementById("adminBody").innerHTML=`<div class="admin-grid"><div class="admin-box"><h3>📊 Dashboard</h3><p>${db.districts.length} loaded districts • ${db.divisions.length} divisions</p></div><div class="admin-box"><h3>🔐 Security</h3><p>Code Change + escalating lockout-এর backend implementation-এর জন্য structure প্রস্তুত।</p><button class="btn light" onclick="alert('Production version-এ code server-side hash হিসেবে রাখা হবে।')">Code Change</button></div><div class="admin-box"><h3>📍 District</h3><button class="btn" onclick="districtForm()">+ Add District</button></div><div class="admin-box"><h3>📸 Pictures</h3><p>Cover image, gallery, people, food ও place images-এর field রাখা হয়েছে।</p></div><div class="admin-box"><h3>🧩 Dynamic Sections</h3><p>নতুন section/category যোগ করার CMS structure।</p></div><div class="admin-box"><h3>💾 Backup</h3><button class="btn light" onclick="backup()">Export JSON</button></div></div><div class="section-title"><h2>District Manager</h2></div><div class="list-grid">${db.districts.map(d=>`<div class="list-card"><h3>${d.name}</h3><p>${d.division} • ${d.region}</p><button class="btn light" onclick="districtForm('${d.id}')">Edit</button> <button class="btn red" onclick="removeDistrict('${d.id}')">Delete</button></div>`).join("")}</div>`}
function districtForm(id=""){let d=db.districts.find(x=>x.id===id)||{name:"",en:"",division:"",region:"",famous:[],food:[],places:[],river:[],history:"",img:""};document.getElementById("adminBody").innerHTML=`<div class="form"><h2>${id?"✏️ Edit":"➕ Add"} District</h2><input id="fn" placeholder="জেলার নাম" value="${esc(d.name)}"><input id="fe" placeholder="English name" value="${esc(d.en)}"><input id="fd" placeholder="বিভাগ" value="${esc(d.division)}"><input id="fr" placeholder="অঞ্চল" value="${esc(d.region)}"><input id="ff" placeholder="বিখ্যাত বিষয় (comma)" value="${esc(d.famous.join(", "))}"><input id="ffood" placeholder="খাবার (comma)" value="${esc(d.food.join(", "))}"><input id="fp" placeholder="দর্শনীয় স্থান (comma)" value="${esc(d.places.join(", "))}"><input id="fri" placeholder="নদী (comma)" value="${esc(d.river.join(", "))}"><textarea id="fh" placeholder="ইতিহাস">${esc(d.history)}</textarea><input id="fi" placeholder="Cover Image URL" value="${esc(d.img)}"><button class="btn" onclick="saveDistrict('${id}')">Save</button><button class="btn light" onclick="adminDashboard()">Back</button></div>`}
function split(s){return s.split(",").map(x=>x.trim()).filter(Boolean)}
function saveDistrict(id){let obj={id:id||("district-"+Date.now()),name:fn.value,en:fe.value,division:fd.value,region:fr.value,famous:split(ff.value),food:split(ffood.value),places:split(fp.value),river:split(fri.value),history:fh.value,img:fi.value,area:"Admin থেকে আপডেটযোগ্য",upazila:"—",est:"—"};let i=db.districts.findIndex(x=>x.id===id);if(i>=0)db.districts[i]=obj;else db.districts.push(obj);save();adminDashboard()}
function removeDistrict(id){if(confirm("District delete করবেন?")){db.districts=db.districts.filter(x=>x.id!==id);save();adminDashboard()}}
function backup(){let b=new Blob([JSON.stringify(db,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="bangladesh-explorer-backup.json";a.click();URL.revokeObjectURL(a.href)}

go("home");
